// appState
export const CHANGE_VIEW = 'CHANGE_VIEW';
export const SET_LOGIN_INFO = 'SET_LOGIN_INFO';

// userState
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS"
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST"
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED"