//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POFtpSender.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OffDate {
            get {
                return ((string)(this["OffDate"]));
            }
            set {
                this["OffDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Uni0iJUkooAt9+W+sfxiufagUeUC7Wxiay9PeS/E/LPnWrZaT8cAfJBelxQui8OU6kbkpkOmXleih4Rphpl8OFkpYjj2mp190QgnTpYMPYtRQ6HERdGIWt2o5BVr4lYwOSFXpHqkGU4Rrh3k7N5TjAzxU4wXxvzyv810KiP3GzcWVw55aS4prgorVK3Rxtwx5wlGN9yrDjnv2fBA6MiXPdsZawo67Er0D4aoOb5mQ4MIVNfYhiXddyHq9MYpcDSWGWJJH1/IDetAX1vyagqx1OtfU68b1ojujWPhQI27kQe9TS6Cfj5qM3iPGKlpF7zmrVXahFZ8XcolTsKK2r5lBIqkpaCC0oQQ2Twm/By3Cjw=")]
        public string FtpUserCredential {
            get {
                return ((string)(this["FtpUserCredential"]));
            }
            set {
                this["FtpUserCredential"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"JlECmyNv4owx3uI80zxn2ee3KB54ZbxiTGd6x6na5RII1Q7GsA3FOEbKmmYuKi+4cFSr6rRhb937e4aIMK2gt7cZr0mpaONMojdjnIftUQNd25wFVVVKMns1wvgQvSmPknKy5hKwgCkoqfW4ZB/d9UelP21RhbQ4wYQMfCUM3HFOlGvsT/EXASuv+MQadrieTTWsQ/3X22E4bEKtZv/TZ23QHqxbs6Bb/SS/Zek3dbC9vx+Mt1lVK8X2Ludmo62nPtLsLZAcWQt8XgvSJX2VNKhS3MNbxT//24S7rx+1Xjw7+7QA319YmHPUpamaQHqYDJIrKxy3d6ej+8HyqijbiS7T3dkUZNF27L8GpM+VjmY=")]
        public string FtpPassCredential {
            get {
                return ((string)(this["FtpPassCredential"]));
            }
            set {
                this["FtpPassCredential"] = value;
            }
        }
    }
}
